[platformio]
default_envs = esp32-c6

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    mathieucarbou/AsyncTCP @ ^3.2.5
    mathieucarbou/ESPAsyncWebServer @ ^3.1.5
    makuna/NeoPixelBus @ ^2.8.0
    knolleary/PubSubClient @ ^2.8
    
build_flags =
    -I include

[env:esp32dev]
board = esp32dev

[env:esp32-c6]
board = esp32-c6-devkitc-1
platform = https://github.com/pioarduino/platform-espressif32.git
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
